services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile.bitnami-spark
    hostname: spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_MASTER_WEBUI_PORT=8081
      - SPARK_LOCAL_IP=spark
      - SPARK_PUBLIC_DNS=localhost
    ports:
      - 8081:8081
    cpus: 1

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile.bitnami-spark
    hostname: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_WORKER_WEBUI_PORT=8091
      - SPARK_LOCAL_IP=spark-worker
      - SPARK_PUBLIC_DNS=localhost
    ports:
      - 8091:8091
    cpus: 1
