services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-04-18T19-09-19Z
    ports:
      - 9001:9001
    volumes:
      - ../minio/data:/data
    environment:
      - MINIO_ROOT_USER=minio_root_user
      - MINIO_ROOT_PASSWORD=minio_root_password
    command: server /data --console-address ":9001"
